version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    # command: ["postgres", "-c", "log_statement=all"]
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./db-setup/azure-mock.sql:/docker-entrypoint-initdb.d/init.sql:ro

  

volumes:
  db-data:
